### ISSUE TITLE
User-oriented themes (readability)

### ISSUE THREAD

**Issue by ooodragon94** [dginev/ar5iv#72]
Thank you for your awesome work!

the default font has very low readability, can you give us an option to change it?
or I would rather prefer calibri!!

thank you@

**Comment by dginev** [comment]
Somewhat related to #68 .

@ooodragon94 could you share a screenshot of what you are seeing and also let me know of your specific browser and operating system? Thanks!

There is certainly an opportunity to add different custom themes, and I think with a little care we can do that well.

**Comment by dginev** [comment]
Right, very helpful screenshot -- this is exactly the same problem reported at #68, where you don't have the prescribed fronts installed on your local system. I should start bundling them with the web service.

Could you still let me know of the browser you are using and on what Operating System (Windows/MacOS/Linux)? Thanks

**Comment by dginev** [comment]
For comparison, @ooodragon94 here is a screenshot of how it would render if you had all fonts -- what are your thoughts on those visuals?

![image](https://user-images.githubusercontent.com/348975/154070878-20c82235-3f3f-4b56-95e7-c837440fdc15.png)

**Comment by ooodragon94** [comment]
For my environment: I use [whale](https://whale.naver.com/) which is built on chrome, I think (many koreans use it)
And I use window ATM.
I am planning to use ar5iv a lot when I buy a tablet.

Your screenshot looks awesome.
Yes, fonts are mainly personal preferences.
I'm so grad that you are planning to embed this feature within ar5iv.
I wish the best luck on this project. It is going to be very useful.

**Comment by ooodragon94** [comment]
Do you mind sharing instructions on installing "prescribed fonts"?

**Comment by dginev** [comment]
Hi @ooodragon94 , I deployed an attempt at fixing the problem with the font assets. Could you do a hard refresh and check if the fonts are now successfully loading when you visit ar5iv?

**Comment by ooodragon94** [comment]
not sure why
but it seems like other pages work well with my preferred font
However https://ar5iv.org/html/2012.00321 still seems like it is not applied...
I tried deleting cache but still not applied

**Comment by ooodragon94** [comment]
![image](https://user-images.githubusercontent.com/34847452/154259750-7841f2f7-79c3-4e4f-8147-fd81de8a6351.png)
It is still the same
Not sure why but it seems like it only shows up like this only on this paper.

Another problem!
https://arxiv.org/abs/2101.10633
This page seems to be not supported

**Comment by dginev** [comment]
If it is only for this paper, should I understand that other papers now look better? If so, it is indeed a matter of updating the assets, which the browser will due once in a while.

I will also start versioning the main site CSS, which will force an update some time later this week. 

For `2101.10633`, I just checked and our latexml conversion encountered problems that did not allow it to return any output -- which is why it looks as if it is missing. I opened a new issue for it in #74

**Comment by ooodragon94** [comment]
thank you for your hard work!

**Comment by dginev** [comment]
Ok, @ooodragon94 I uploaded the change I referred to - the site CSS will now inevitably be reloaded on your end. 

If you now visit the page and are *still* seeing it as before, I would have to ask you to open your browser console and check for error messages. The assets would have to be getting blocked, or be seen as broken, for failures from here on.

https://ar5iv.org/html/2012.00321

**Comment by ooodragon94** [comment]
![image](https://user-images.githubusercontent.com/34847452/154266002-59b44372-dec4-4090-9c30-ea8a2d652ef5.png)
awesome

**Comment by dginev** [comment]
Alright, great to see it finally fixed! Let's close here and move to other issues.

Thanks for the patience and troubleshooting with me, it was a big help!
